// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SkincareBookingService.DAL.Entities;

public partial class Account
{
    public int AccountId { get; set; }

    public string AccountName { get; set; }

    public string Password { get; set; }

    public string Role { get; set; }

    public bool Active { get; set; }

    public virtual ICollection<Customer> Customers { get; set; } = new List<Customer>();

    public virtual ICollection<SkinTherapist> SkinTherapists { get; set; } = new List<SkinTherapist>();
}