// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SkincareBookingService.DAL.Entities;

public partial class CustomerSurveyAnswer
{
    public int CustomersurveyanswerId { get; set; }

    public int? CustomersurveyId { get; set; }

    public int? AnswerId { get; set; }

    public virtual QuizAnswer Answer { get; set; }

    public virtual CustomerSurvey Customersurvey { get; set; }
}