// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SkincareBookingService.DAL.Entities;

public partial class CustomerSurvey
{
    public int CustomersurveyId { get; set; }

    public DateTime? Date { get; set; }

    public int? SkintypeId { get; set; }

    public int? QuestionsId { get; set; }

    public int? CustomerId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual ICollection<CustomerSurveyAnswer> CustomerSurveyAnswers { get; set; } = new List<CustomerSurveyAnswer>();

    public virtual QuizQuestionSet Questions { get; set; }

    public virtual SkinType Skintype { get; set; }
}