// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SkincareBookingService.DAL.Entities;

public partial class Customer
{
    public int CustomerId { get; set; }

    public string Name { get; set; }

    public int? SkintypeId { get; set; }

    public int? AccountId { get; set; }

    public string PhoneNumber { get; set; }

    public string Image { get; set; }

    public string Email { get; set; }

    public virtual Account Account { get; set; }

    public virtual ICollection<Blog> Blogs { get; set; } = new List<Blog>();

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    public virtual ICollection<CustomerSurvey> CustomerSurveys { get; set; } = new List<CustomerSurvey>();

    public virtual ICollection<Feedback> Feedbacks { get; set; } = new List<Feedback>();

    public virtual ICollection<QuizAnswer> QuizAnswers { get; set; } = new List<QuizAnswer>();

    public virtual ICollection<Rating> Ratings { get; set; } = new List<Rating>();

    public virtual SkinType Skintype { get; set; }
}