// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SkincareBookingService.DAL.Entities;

public partial class QuizAnswer
{
    public int AnswerId { get; set; }

    public int? QuizquestionId { get; set; }

    public int? SkintypeId { get; set; }

    public string Answer { get; set; }

    public virtual ICollection<CustomerSurveyAnswer> CustomerSurveyAnswers { get; set; } = new List<CustomerSurveyAnswer>();

    public virtual QuizQuestion Quizquestion { get; set; }

    public virtual SkinType Skintype { get; set; }
}