// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace SkincareBookingService.DAL.Entities;

public partial class QuizQuestion
{
    public int QuizquestionId { get; set; }

    public string Content { get; set; }

    public int? QuestionsId { get; set; }

    public virtual QuizQuestionSet Questions { get; set; }

    public virtual ICollection<QuizAnswer> QuizAnswers { get; set; } = new List<QuizAnswer>();
}