// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace SkincareBookingService.DAL.Entities;

public partial class Schedule
{
    public int ScheduleId { get; set; }

    public int SkinTherapistId { get; set; }

    public int SlotId { get; set; }

    public DateTime Date { get; set; }

    public virtual SkinTherapist SkinTherapist { get; set; }

    public virtual Slot Slot { get; set; }
}