// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SkincareBookingService.DAL.Entities;

public partial class SkinTherapistService
{
    public int SkintherapistserviceId { get; set; }

    public string Name { get; set; }

    public string Speciality { get; set; }

    public string Email { get; set; }

    public string Experience { get; set; }

    public int? SkintherapistId { get; set; }

    public int? ServiceId { get; set; }

    public virtual Service Service { get; set; }

    public virtual SkinTherapist Skintherapist { get; set; }

    public static implicit operator SkinTherapistService(List<SkinTherapistService> v)
    {
        throw new NotImplementedException();
    }
}