// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SkincareBookingService.DAL.Entities;

public partial class SkinType
{
    public int SkintypeId { get; set; }

    public string SkintypeName { get; set; }

    public string Description { get; set; }

    public string Image { get; set; }

    public string Status { get; set; }

    public string Pros { get; set; }

    public string Cons { get; set; }

    public string SkincareGuide { get; set; }

    public string Introduction { get; set; }

    public virtual ICollection<CustomerSurvey> CustomerSurveys { get; set; } = new List<CustomerSurvey>();

    public virtual ICollection<Customer> Customers { get; set; } = new List<Customer>();

    public virtual ICollection<QuizAnswer> QuizAnswers { get; set; } = new List<QuizAnswer>();

    public virtual ICollection<SkintypeService> SkintypeServices { get; set; } = new List<SkintypeService>();
}