// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SkincareBookingService.DAL.Entities;

public partial class SkintypeService
{
    public int SkintypeServiceId { get; set; }

    public int? SkintypeId { get; set; }

    public int? ServiceId { get; set; }

    public virtual Service Service { get; set; }

    public virtual SkinType Skintype { get; set; }
}