// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SkincareBookingService.DAL.Entities;

public partial class Slot
{
    public int SlotId { get; set; }

    public string Status { get; set; }

    public string Time { get; set; }

    public int? BookingId { get; set; }

    public virtual Booking Booking { get; set; }

    public virtual ICollection<Schedule> Schedules { get; set; } = new List<Schedule>();
}